events {}

http {
    server {
        listen 80;
        server_name 127.0.0.1;

        location /service1 {
            proxy_pass http://service1:8000/;
        }

        location /service2  {
            proxy_pass http://service2:8001/;
        }
    }
}