version: '3'

services:
  service1:
    build: .
    container_name: service1
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
    networks:
      - my_network

  celery_worker_1:
    build: .
    container_name: celery_worker_1
    command: celery -A celery_worker worker --loglevel=info -Q service1_queue
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
    networks:
      - my_network
    
networks:
  my_network:
    external: true